import { Inter } from "next/font/google";
import Footer from "./utilities/Footer/Footer";
import NavBar from "./utilities/NavBar/NavBar";
import "../StylePages/StylePages.scss";
import ChangeThemes from "./ChangeThemes/ChangeThemes";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Test Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChangeThemes>
          <NavBar />
          {children}
          <Footer />
        </ChangeThemes>
      </body>
    </html>
  );
}
